language: node_js
node_js:
    - "6.11.0"
branches:
  only:
      - staging
      - master
install:
    - npm install
script:
    - karma start
services:
  - mongodb
cache: 
  - npm install
notifications:
  webhooks: $COVERALLS_URL
